- repo: https://github.com/tekwizely/pre-commit-golang
  rev: master
  hooks:
#    #
#    # Go Build
#    #
#    -   id: go-build-mod
#    -   id: go-build-pkg
#    -   id: go-build-repo-mod
#    -   id: go-build-repo-pkg
#    #
#    # Go Test
#    #
    -   id: go-test-mod
#    #
#    # Go Vet
#    #
    -   id: go-vet-mod
#    #
#    # Formatters
#    #
    -   id: go-returns
#    #
#    # Style Checkers
#    #
    -   id: go-lint
    -   id: go-critic
#    #
#    # GolangCI-Lint
#    # - Fast Multi-Linter
#    # - Can be configured to replace MOST other hooks
#    # - Supports repo config file for configuration
#    # - https://github.com/golangci/golangci-lint
#    #
#    -   id: golangci-lint
    -   id: golangci-lint-mod
#    -   id: golangci-lint-pkg
#    -   id: golangci-lint-repo-mod
#    -   id: golangci-lint-repo-pkg